sudo: false
dist: trusty
language: node_js
node_js: 8.0

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - polymer install

before_script:
  - gulp lint
  - polymer lint --rules polymer-2-hybrid --input *.html
  - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || TRAVIS_BRANCH=quick/${TRAVIS_BUILD_ID} xvfb-run -s '-screen 0 1024x768x24' polymer test -l chrome -l firefox)

script:
  - xvfb-run -s '-screen 0 1024x768x24' polymer test
  - travis_retry gemini test test/visual
