language: node_js
node_js:
  - 6
dist: trusty
sudo: required
env:
  global:
  - TMPDIR=$TRAVIS_BUILD_DIR/tmp
# https://iamakulov.com/notes/all/install-google-chrome-on-travis/
addons:
  apt:
    packages:
      - google-chrome-stable
before_script:
  - npm install bower web-component-tester
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: ./run_tests.sh -l chrome
