language: node_js
node_js:
  - "4"
  - "6"
  - "7"
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script: xvfb-run npm test
